; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://platformio.org

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# Forces PlatformIO to scan deep nested dependencies inside external libraries
lib_ldf_mode = deep+

lib_deps = 
    adafruit/Adafruit MAX31865 library@^1.6.2
    Wire
    SPI